apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: orixon
data:
  NODE_ENV: "production"
  APP_URL: "https://your-domain.example"
  NEXT_PUBLIC_APP_URL: "https://your-domain.example"
  NEXT_PUBLIC_APP_NAME: "Ситрук"
  NEXT_PUBLIC_APP_SHORT_NAME: "Acme"
